// Generated by scripts/generate-dts.js from the veneer registry — do not edit.
// Regenerate with `npm run types`; test/dts.test.js fails when this is stale.

export type TypeName =
  "s32" | "u32" | "s64" | "u64" | "f32" | "f64" | "bool" | "funcref" | "externref" | "exnref" | "anyref" | "eqref" | "i31ref" | "structref" | "arrayref" | "s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2";

/** Typed function reference brand: (ref $sig) / (ref null $sig). */
export type RefBrand<
  P extends readonly WasmType[] = any, R extends readonly WasmType[] = any,
  N extends boolean = boolean> = { readonly __refParams: P; readonly __refResults: R; readonly __nullable: N };
/** GC struct/array reference brand; fields flow structurally. */
export type GCBrand<F = any, N extends boolean = boolean> = { readonly __gcFields: F; readonly __gcNullable: N };
export type TypeTag = TypeName | RefBrand | GCBrand;
type AnyHier = "anyref" | "eqref" | "i31ref" | "structref" | "arrayref" | GCBrand;

/** A single-value expression of builder-level type T. */
export interface Expr<T extends TypeTag = TypeTag> {
  readonly __wasmloom: T;
}

/** Safe value-exact promotion: what an operand slot of type T accepts. */
type Accepts = {
  s32: "s32" | "bool";
  u32: "u32" | "bool";
  s64: "s64" | "s32" | "u32" | "bool";
  u64: "u64" | "u32" | "bool";
  f32: "f32" | "bool";
  f64: "f64" | "f32" | "s32" | "u32" | "bool";
  bool: "bool";
  funcref: "funcref";
  externref: "externref";
  exnref: "exnref";
  anyref: "anyref";
  eqref: "eqref";
  i31ref: "i31ref";
  structref: "structref";
  arrayref: "arrayref";
  s8x16: "s8x16";
  u8x16: "u8x16";
  s16x8: "s16x8";
  u16x8: "u16x8";
  s32x4: "s32x4";
  u32x4: "u32x4";
  s64x2: "s64x2";
  u64x2: "u64x2";
  f32x4: "f32x4";
  f64x2: "f64x2";
  m8x16: "m8x16";
  m16x8: "m16x8";
  m32x4: "m32x4";
  m64x2: "m64x2";
};
// funcref slots also take any typed function reference (upcast promotion);
// nullable ref slots take the non-null form (structural: false <: boolean).
export type Into<T extends TypeTag> =
  T extends "funcref" ? Expr<"funcref"> | Expr<RefBrand>
  : T extends "anyref" ? Expr<AnyHier>
  : T extends "eqref" ? Expr<"eqref" | "i31ref" | "structref" | "arrayref" | GCBrand>
  : T extends "structref" | "arrayref" ? Expr<T | GCBrand>
  : T extends keyof Accepts ? Expr<Accepts[T] & TypeName>
  : T extends RefBrand<infer P, infer R, infer N>
    ? (N extends true ? Expr<RefBrand<P, R, boolean>> : Expr<RefBrand<P, R, false>>)
  : T extends GCBrand<infer F, infer N>
    ? (N extends true ? Expr<GCBrand<F, boolean>> : Expr<GCBrand<F, false>>)
  : never;
type I32ish = Expr<"s32" | "u32" | "bool">; // sign-agnostic 32-bit positions

export interface MemOpts {
  /** byte alignment hint, a power of two ≤ the access size (default: natural) */
  align?: number;
  /** constant byte offset added to the address (default: 0) */
  offset?: number;
}

/** The value-level face of a type: a token for declarations. */
export interface WasmType<T extends TypeTag = TypeTag> {
  readonly name: string;
  readonly __type?: T;
}

type NameOf<W> = W extends WasmType<infer T> ? T : never;
type VarsOf<P extends readonly WasmType[]> = { [K in keyof P]: Var<NameOf<P[K]>> };
type IntoArgs<P extends readonly WasmType[]> = { [K in keyof P]: Into<NameOf<P[K]>> };
type CallResult<R extends readonly WasmType[]> =
  R extends readonly [] ? void : R extends readonly [WasmType<infer T>] ? Expr<T> : VarsOf<R>;

/** A function-scoped variable (wasm local). Reads by using it as a value. */
export interface Var<T extends TypeTag = TypeTag> extends Expr<T> {
  set(value: Into<T>): void;
}

/** A module-scoped variable (wasm global). */
export interface Global<T extends TypeTag = TypeTag> extends Expr<T> {
  set(value: Into<T>): void;
  import(module: string, name: string): this;
  export(name: string): this;
  immutable(): this;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

export interface Label {
  /** Pin a forward-declared label at the current position. Exactly once. */
  here(): Label;
}

export interface IfChain<R extends readonly WasmType[]> {
  elseIf(cond: Into<"bool">, body: (ctx: Ctx<R>) => void): IfChain<R>;
  else(body: (ctx: Ctx<R>) => void): void;
}

/** The `$` statement context passed to body callbacks. */
export interface Ctx<R extends readonly WasmType[] = WasmType[]> {
  label: { (): Label; ahead(): Label };
  variable<W extends WasmType>(type: W, init?: Into<NameOf<W>> | number | bigint | boolean): Var<NameOf<W>>;
  goto(target: Label): void;
  gotoIf(cond: Into<"bool">, target: Label): void;
  switch(index: I32ish, targets: readonly Label[], defaultTarget: Label): void;
  /** Returning a call's results directly emits a tail call (return_call). */
  return(...values: IntoArgs<R>): void;
  /** Throw an exception with the tag's payload. A terminator, like return. */
  throw<CP extends readonly WasmType[]>(tag: Tag<CP>, ...args: IntoArgs<CP>): void;
  /** Rethrow a caught exception (exnref), preserving its identity. */
  throwRef(exn: Into<"exnref">): void;
  /** Protected region; handlers chain after. Bodies are control-flow islands. */
  try(body: (ctx: Ctx<R>) => void): TryChain<R>;
  drop(value: Expr): void;
  unreachable(): void;
  /** atomic.fence — order memory effects without touching memory. */
  fence(): void;
  if(cond: Into<"bool">, body: (ctx: Ctx<R>) => void): IfChain<R>;
  while(cond: Into<"bool">, body: (ctx: Ctx<R>) => void): void;
}

export interface Func<P extends readonly WasmType[] = WasmType[], R extends readonly WasmType[] = WasmType[]> {
  body(cb: (...args: [...VarsOf<P>, Ctx<R>]) => void): this;
  import(module: string, name: string): this;
  export(name: string): this;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
  /** Precise non-null reference (ref $sig); upcasts are promotions. */
  ref(): Expr<RefBrand<P, R, false>>;
  /** This function's signature as an interned funcType handle. */
  readonly type: FuncType<P, R>;
  call(...args: IntoArgs<P>): CallResult<R>;
}

export interface NonNullRefType<P extends readonly WasmType[], R extends readonly WasmType[]>
  extends WasmType<RefBrand<P, R, false>> {
  /** Checked nullable→non-null bridge (ref.as_non_null — traps on null). */
  of(x: Expr<RefBrand<P, R, boolean>>): Expr<RefBrand<P, R, false>>;
}
export interface NullableRefType<P extends readonly WasmType[], R extends readonly WasmType[]>
  extends WasmType<RefBrand<P, R, true>> {
  null(): Expr<RefBrand<P, R, true>>;
  is_null(x: Expr<RefBrand<P, R, boolean>>): Expr<"bool">;
}
export interface FuncType<P extends readonly WasmType[] = WasmType[], R extends readonly WasmType[] = WasmType[]> {
  readonly params: P;
  readonly results: R;
  /** (ref $sig) — non-null typed function reference type. */
  readonly ref: NonNullRefType<P, R>;
  /** (ref null $sig). */
  readonly refNull: NullableRefType<P, R>;
  /** call_ref through a typed reference (traps on null). Tail in $.return. */
  call(ref: Expr<RefBrand<P, R, boolean>>, ...args: IntoArgs<P>): CallResult<R>;
}

/** An exception tag: the typed signature of thrown values (wasm 3.0 EH). */
export interface Tag<P extends readonly WasmType[] = WasmType[]> {
  readonly params: P;
  import(module: string, name: string): this;
  export(name: string): this;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

export interface TryChain<R extends readonly WasmType[]> {
  /** First matching clause wins; the payload arrives as typed variables. */
  catch<CP extends readonly WasmType[]>(
    tag: Tag<CP>, cb: (...args: [...VarsOf<CP>, Ctx<R>]) => void): TryChain<R>;
  /** Like catch, plus an exnref for $.throwRef rethrows. */
  catchRef<CP extends readonly WasmType[]>(
    tag: Tag<CP>, cb: (...args: [...VarsOf<CP>, Var<"exnref">, Ctx<R>]) => void): TryChain<R>;
  catchAll(cb: (ctx: Ctx<R>) => void): TryChain<R>;
  catchAllRef(cb: (exn: Var<"exnref">, ctx: Ctx<R>) => void): TryChain<R>;
}

/** Packed field storage (struct/array fields only). */
export interface PackedType { readonly packed: 8 | 16; readonly name: string }
export type FieldSpec = WasmType | PackedType | { __imm: WasmType | PackedType };
/** Mark a struct/array field immutable. */
export function imm<T extends WasmType | PackedType>(t: T): { __imm: T };
export const i8: PackedType;
export const i16: PackedType;

type Unimm<F> = F extends { __imm: infer T } ? T : F;
type DataKeys<F> = { [K in keyof F]: Unimm<F[K]> extends PackedType ? never : K }[keyof F];
type PackedKeys<F> = { [K in keyof F]: Unimm<F[K]> extends PackedType ? K : never }[keyof F];
type MutableKeys<F> = { [K in keyof F]: F[K] extends { __imm: any } ? never : K }[keyof F];
type FieldTag<F, K extends keyof F> = NameOf<Unimm<F[K]>>;
type GCRef<F, N extends boolean> = Expr<GCBrand<F, N>>;

export interface GCRefType<F, N extends boolean> extends WasmType<GCBrand<F, N>> {
  /** Checked, trapping downcast (ref.cast). */
  of(x: Expr<AnyHier>): GCRef<F, N>;
}
export interface NullableGCRefType<F> extends GCRefType<F, true> {
  null(): GCRef<F, true>;
  is_null(x: GCRef<F, boolean>): Expr<"bool">;
}

export interface StructType<F extends Record<string, FieldSpec> = Record<string, FieldSpec>> {
  readonly ref: GCRefType<F, false>;
  readonly refNull: NullableGCRefType<F>;
  fields(spec: F, opts?: { extends?: StructType<any> }): this;
  new(...values: Array<Expr | Var | Global>): GCRef<F, false>;
  newDefault(): GCRef<F, false>;
  get<K extends DataKeys<F>>(x: GCRef<F, boolean>, field: K): Expr<FieldTag<F, K>>;
  getS<K extends PackedKeys<F>>(x: GCRef<F, boolean>, field: K): Expr<"s32">;
  getU<K extends PackedKeys<F>>(x: GCRef<F, boolean>, field: K): Expr<"u32">;
  set<K extends MutableKeys<F> & DataKeys<F>>(x: GCRef<F, boolean>, field: K, value: Into<FieldTag<F, K>>): void;
  set<K extends MutableKeys<F> & PackedKeys<F>>(x: GCRef<F, boolean>, field: K, value: I32ish): void;
  /** Non-trapping type probe (ref.test). */
  test(x: Expr<AnyHier>): Expr<"bool">;
}

export interface ArrayType<E extends FieldSpec = FieldSpec> {
  readonly ref: GCRefType<{ element: E }, false>;
  readonly refNull: NullableGCRefType<{ element: E }>;
  element(spec: E): this;
  new(len: I32ish, init?: Unimm<E> extends PackedType ? I32ish : Into<NameOf<Unimm<E>>>): GCRef<{ element: E }, false>;
  newFixed(...values: Array<Expr | Var | Global>): GCRef<{ element: E }, false>;
  newData(seg: DataSegment, offset: I32ish, len: I32ish): GCRef<{ element: E }, false>;
  get(x: GCRef<{ element: E }, boolean>, index: I32ish): Expr<NameOf<Unimm<E>>>;
  getS(x: GCRef<{ element: E }, boolean>, index: I32ish): Expr<"s32">;
  getU(x: GCRef<{ element: E }, boolean>, index: I32ish): Expr<"u32">;
  set(x: GCRef<{ element: E }, boolean>, index: I32ish, value: Unimm<E> extends PackedType ? I32ish : Into<NameOf<Unimm<E>>>): void;
  len(x: GCRef<{ element: E }, boolean>): Expr<"u32">;
  fill(x: GCRef<{ element: E }, boolean>, offset: I32ish, value: Unimm<E> extends PackedType ? I32ish : Into<NameOf<Unimm<E>>>, len: I32ish): void;
  copy(dst: GCRef<{ element: E }, boolean>, dstOff: I32ish, src: GCRef<{ element: E }, boolean>, srcOff: I32ish, len: I32ish): void;
  initData(x: GCRef<{ element: E }, boolean>, dstOff: I32ish, seg: DataSegment, srcOff: I32ish, len: I32ish): void;
  /** Non-trapping type probe (ref.test). */
  test(x: Expr<AnyHier>): Expr<"bool">;
}

export interface Limits { min: number; max?: number; shared?: boolean }

export interface Memory {
  size(): Expr<"u32">;
  grow(delta: I32ish): Expr<"u32">;
  fill(dst: I32ish, value: I32ish, len: I32ish): void;
  copy(dst: I32ish, src: I32ish, len: I32ish, opts?: { from?: Memory }): void;
  init(seg: DataSegment, dst: I32ish, src: I32ish, len: I32ish): void;
  /** Wake up to count waiters at addr; u32 woken count. */
  notify(addr: I32ish, count: I32ish): Expr<"u32">;
  /** Block while addr holds expected. u32: 0 woken, 1 mismatch, 2 timeout. */
  wait32(addr: I32ish, expected: I32ish, timeoutNs: Into<"s64">): Expr<"u32">;
  wait64(addr: I32ish, expected: Into<"s64">, timeoutNs: Into<"s64">): Expr<"u32">;
  import(module: string, name: string): this;
  export(name: string): this;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

export interface Table<E extends TypeTag = "funcref"> {
  get(index: I32ish): Expr<E>;
  set(index: I32ish, value: Into<E>): void;
  size(): Expr<"u32">;
  grow(delta: I32ish, init?: Into<E>): Expr<"u32">;
  fill(start: I32ish, value: Into<E>, len: I32ish): void;
  copy(dst: I32ish, src: I32ish, len: I32ish, opts?: { from?: Table<E> }): void;
  init(seg: ElemSegment, dst: I32ish, src: I32ish, len: I32ish): void;
  call<P extends readonly WasmType[], R extends readonly WasmType[]>(
    type: FuncType<P, R>, index: I32ish, ...args: IntoArgs<P>): CallResult<R>;
  import(module: string, name: string): this;
  export(name: string): this;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

type ConstOffset = number | Expr<"s32" | "u32"> | Global<"s32" | "u32">;

export interface DataSegment {
  at(mem: Memory, offset: ConstOffset): this;
  drop(): void;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

export interface ElemSegment {
  at(table: Table<any>, offset: ConstOffset): this;
  drop(): void;
  /** Debug name for the name section (overrides export/import-derived). */
  name(name: string): this;
}

type GlobalInit<T extends TypeTag> =
  Into<T> | Global<T> | null | number | bigint | boolean | readonly (number | bigint)[];

export class Module {
  constructor(opts?: { debug?: boolean; permissive?: boolean; tailCalls?: boolean; names?: boolean });
  function<const P extends readonly WasmType[], const R extends readonly WasmType[]>(params: P, results: R): Func<P, R>;
  function<P extends readonly WasmType[], R extends readonly WasmType[]>(type: FuncType<P, R>): Func<P, R>;
  funcType<const P extends readonly WasmType[], const R extends readonly WasmType[]>(params: P, results: R): FuncType<P, R>;
  variable<W extends WasmType>(type: W, init?: GlobalInit<NameOf<W>>): Global<NameOf<W>>;
  tag<const P extends readonly WasmType[]>(params: P): Tag<P>;
  /** GC struct type. Omit fields and call .fields() later for recursion. */
  struct<F extends Record<string, FieldSpec>>(fields?: F, opts?: { extends?: StructType<any> }): StructType<F>;
  /** GC array type. Omit the element and call .element() later. */
  array<E extends FieldSpec>(element?: E): ArrayType<E>;
  memory(limits: Limits): Memory;
  table<E extends WasmType<"funcref"> | WasmType<"externref"> | NullableRefType<readonly WasmType[], readonly WasmType[]>>(
    elemType: E, limits: Limits): Table<NameOf<E>>;
  data(bytes: Uint8Array | ArrayBuffer): DataSegment;
  elem(items: readonly (Func<any, any> | null)[]): ElemSegment;
  start(fn: Func<any, any>): this;
  /** Module debug name for the name section. */
  name(name: string): this;
  emit(): Uint8Array;
}

export class WasmLoomError extends Error {}

export interface Ns_s32 extends WasmType<"s32"> {
  const(value: number): Expr<"s32">;
  cast(x: Expr<"u32" | "bool"> | Var<"u32" | "bool"> | Global<"u32" | "bool">): Expr<"s32">;
  add(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  sub(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  mul(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  and(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  or(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  xor(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  shl(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  rotl(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  rotr(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  clz(a: Into<"s32">): Expr<"s32">;
  ctz(a: Into<"s32">): Expr<"s32">;
  popcnt(a: Into<"s32">): Expr<"s32">;
  eqz(a: Into<"s32">): Expr<"bool">;
  eq(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  ne(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  div(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  rem(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  shr(a: Into<"s32">, b: Into<"s32">): Expr<"s32">;
  lt(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  gt(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  le(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  ge(a: Into<"s32">, b: Into<"s32">): Expr<"bool">;
  extend8(a: Into<"s32">): Expr<"s32">;
  extend16(a: Into<"s32">): Expr<"s32">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32">;
  store(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32">;
  load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32">;
  store8(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  store16(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  atomic_load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32">;
  atomic_store(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  atomic_store8(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  atomic_store16(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: MemOpts): void;
  atomic_add(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_sub(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_and(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_or(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_xor(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_xchg(mem: Memory, addr: I32ish, value: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  atomic_cmpxchg(mem: Memory, addr: I32ish, a: Into<"s32">, b: Into<"s32">, opts?: { offset?: number }): Expr<"s32">;
  wrap(a: Into<"s64">): Expr<"s32">;
  wrap(a: Into<"u64">): Expr<"s32">;
  trunc(a: Into<"f32">): Expr<"s32">;
  trunc(a: Into<"f64">): Expr<"s32">;
  trunc_sat(a: Into<"f32">): Expr<"s32">;
  trunc_sat(a: Into<"f64">): Expr<"s32">;
  reinterpret(a: Into<"f32">): Expr<"s32">;
  select(a: Into<"bool">, b: Into<"s32">, c: Into<"s32">): Expr<"s32">;
}
export interface Ns_u32 extends WasmType<"u32"> {
  const(value: number): Expr<"u32">;
  cast(x: Expr<"s32" | "bool"> | Var<"s32" | "bool"> | Global<"s32" | "bool">): Expr<"u32">;
  add(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  sub(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  mul(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  and(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  or(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  xor(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  shl(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  rotl(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  rotr(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  clz(a: Into<"u32">): Expr<"u32">;
  ctz(a: Into<"u32">): Expr<"u32">;
  popcnt(a: Into<"u32">): Expr<"u32">;
  eqz(a: Into<"u32">): Expr<"bool">;
  eq(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  ne(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  div(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  rem(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  shr(a: Into<"u32">, b: Into<"u32">): Expr<"u32">;
  lt(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  gt(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  le(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  ge(a: Into<"u32">, b: Into<"u32">): Expr<"bool">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  store(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  store8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  store16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  atomic_load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  atomic_store(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  atomic_store8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  atomic_store16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: MemOpts): void;
  atomic_add(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_sub(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_and(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_or(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xor(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xchg(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_cmpxchg(mem: Memory, addr: I32ish, a: Into<"u32">, b: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  atomic_add8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_sub8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_and8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_or8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xor8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xchg8(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_cmpxchg8(mem: Memory, addr: I32ish, a: Into<"u32">, b: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32">;
  atomic_add16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_sub16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_and16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_or16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xor16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_xchg16(mem: Memory, addr: I32ish, value: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  atomic_cmpxchg16(mem: Memory, addr: I32ish, a: Into<"u32">, b: Into<"u32">, opts?: { offset?: number }): Expr<"u32">;
  wrap(a: Into<"s64">): Expr<"u32">;
  wrap(a: Into<"u64">): Expr<"u32">;
  trunc(a: Into<"f32">): Expr<"u32">;
  trunc(a: Into<"f64">): Expr<"u32">;
  trunc_sat(a: Into<"f32">): Expr<"u32">;
  trunc_sat(a: Into<"f64">): Expr<"u32">;
  reinterpret(a: Into<"f32">): Expr<"u32">;
  select(a: Into<"bool">, b: Into<"u32">, c: Into<"u32">): Expr<"u32">;
}
export interface Ns_s64 extends WasmType<"s64"> {
  const(value: number | bigint): Expr<"s64">;
  cast(x: Expr<"u64"> | Var<"u64"> | Global<"u64">): Expr<"s64">;
  add(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  sub(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  mul(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  and(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  or(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  xor(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  shl(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  rotl(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  rotr(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  clz(a: Into<"s64">): Expr<"s64">;
  ctz(a: Into<"s64">): Expr<"s64">;
  popcnt(a: Into<"s64">): Expr<"s64">;
  eqz(a: Into<"s64">): Expr<"bool">;
  eq(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  ne(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  div(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  rem(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  shr(a: Into<"s64">, b: Into<"s64">): Expr<"s64">;
  lt(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  gt(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  le(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  ge(a: Into<"s64">, b: Into<"s64">): Expr<"bool">;
  extend8(a: Into<"s64">): Expr<"s64">;
  extend16(a: Into<"s64">): Expr<"s64">;
  extend32(a: Into<"s64">): Expr<"s64">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64">;
  store(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64">;
  load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64">;
  store8(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  store16(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  load32(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64">;
  store32(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  atomic_load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64">;
  atomic_store(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  atomic_store8(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  atomic_store16(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  atomic_store32(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: MemOpts): void;
  atomic_add(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_sub(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_and(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_or(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_xor(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_xchg(mem: Memory, addr: I32ish, value: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  atomic_cmpxchg(mem: Memory, addr: I32ish, a: Into<"s64">, b: Into<"s64">, opts?: { offset?: number }): Expr<"s64">;
  extend(a: Into<"s32">): Expr<"s64">;
  trunc(a: Into<"f32">): Expr<"s64">;
  trunc(a: Into<"f64">): Expr<"s64">;
  trunc_sat(a: Into<"f32">): Expr<"s64">;
  trunc_sat(a: Into<"f64">): Expr<"s64">;
  reinterpret(a: Into<"f64">): Expr<"s64">;
  select(a: Into<"bool">, b: Into<"s64">, c: Into<"s64">): Expr<"s64">;
}
export interface Ns_u64 extends WasmType<"u64"> {
  const(value: number | bigint): Expr<"u64">;
  cast(x: Expr<"s64"> | Var<"s64"> | Global<"s64">): Expr<"u64">;
  add(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  sub(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  mul(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  and(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  or(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  xor(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  shl(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  rotl(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  rotr(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  clz(a: Into<"u64">): Expr<"u64">;
  ctz(a: Into<"u64">): Expr<"u64">;
  popcnt(a: Into<"u64">): Expr<"u64">;
  eqz(a: Into<"u64">): Expr<"bool">;
  eq(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  ne(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  div(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  rem(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  shr(a: Into<"u64">, b: Into<"u64">): Expr<"u64">;
  lt(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  gt(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  le(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  ge(a: Into<"u64">, b: Into<"u64">): Expr<"bool">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  store(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  store8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  store16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  load32(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  store32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  atomic_load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  atomic_store(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  atomic_store8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  atomic_store16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  atomic_store32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: MemOpts): void;
  atomic_add(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_sub(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_and(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_or(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xor(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xchg(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_cmpxchg(mem: Memory, addr: I32ish, a: Into<"u64">, b: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_load8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  atomic_add8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_sub8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_and8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_or8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xor8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xchg8(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_cmpxchg8(mem: Memory, addr: I32ish, a: Into<"u64">, b: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_load16(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  atomic_add16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_sub16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_and16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_or16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xor16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xchg16(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_cmpxchg16(mem: Memory, addr: I32ish, a: Into<"u64">, b: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_load32(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64">;
  atomic_add32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_sub32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_and32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_or32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xor32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_xchg32(mem: Memory, addr: I32ish, value: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  atomic_cmpxchg32(mem: Memory, addr: I32ish, a: Into<"u64">, b: Into<"u64">, opts?: { offset?: number }): Expr<"u64">;
  extend(a: Into<"u32">): Expr<"u64">;
  trunc(a: Into<"f32">): Expr<"u64">;
  trunc(a: Into<"f64">): Expr<"u64">;
  trunc_sat(a: Into<"f32">): Expr<"u64">;
  trunc_sat(a: Into<"f64">): Expr<"u64">;
  reinterpret(a: Into<"f64">): Expr<"u64">;
  select(a: Into<"bool">, b: Into<"u64">, c: Into<"u64">): Expr<"u64">;
}
export interface Ns_f32 extends WasmType<"f32"> {
  const(value: number): Expr<"f32">;
  abs(a: Into<"f32">): Expr<"f32">;
  neg(a: Into<"f32">): Expr<"f32">;
  ceil(a: Into<"f32">): Expr<"f32">;
  floor(a: Into<"f32">): Expr<"f32">;
  trunc(a: Into<"f32">): Expr<"f32">;
  nearest(a: Into<"f32">): Expr<"f32">;
  sqrt(a: Into<"f32">): Expr<"f32">;
  add(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  sub(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  mul(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  div(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  min(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  max(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  copysign(a: Into<"f32">, b: Into<"f32">): Expr<"f32">;
  eq(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  ne(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  lt(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  gt(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  le(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  ge(a: Into<"f32">, b: Into<"f32">): Expr<"bool">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f32">;
  store(mem: Memory, addr: I32ish, value: Into<"f32">, opts?: MemOpts): void;
  convert(a: Into<"s32">): Expr<"f32">;
  convert(a: Into<"u32">): Expr<"f32">;
  convert(a: Into<"s64">): Expr<"f32">;
  convert(a: Into<"u64">): Expr<"f32">;
  demote(a: Into<"f64">): Expr<"f32">;
  reinterpret(a: Into<"s32">): Expr<"f32">;
  reinterpret(a: Into<"u32">): Expr<"f32">;
  select(a: Into<"bool">, b: Into<"f32">, c: Into<"f32">): Expr<"f32">;
}
export interface Ns_f64 extends WasmType<"f64"> {
  const(value: number): Expr<"f64">;
  abs(a: Into<"f64">): Expr<"f64">;
  neg(a: Into<"f64">): Expr<"f64">;
  ceil(a: Into<"f64">): Expr<"f64">;
  floor(a: Into<"f64">): Expr<"f64">;
  trunc(a: Into<"f64">): Expr<"f64">;
  nearest(a: Into<"f64">): Expr<"f64">;
  sqrt(a: Into<"f64">): Expr<"f64">;
  add(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  sub(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  mul(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  div(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  min(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  max(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  copysign(a: Into<"f64">, b: Into<"f64">): Expr<"f64">;
  eq(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  ne(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  lt(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  gt(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  le(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  ge(a: Into<"f64">, b: Into<"f64">): Expr<"bool">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f64">;
  store(mem: Memory, addr: I32ish, value: Into<"f64">, opts?: MemOpts): void;
  convert(a: Into<"s32">): Expr<"f64">;
  convert(a: Into<"u32">): Expr<"f64">;
  convert(a: Into<"s64">): Expr<"f64">;
  convert(a: Into<"u64">): Expr<"f64">;
  promote(a: Into<"f32">): Expr<"f64">;
  reinterpret(a: Into<"s64">): Expr<"f64">;
  reinterpret(a: Into<"u64">): Expr<"f64">;
  select(a: Into<"bool">, b: Into<"f64">, c: Into<"f64">): Expr<"f64">;
}
export interface Ns_bool extends WasmType<"bool"> {
  const(value: boolean): Expr<"bool">;
  and(a: Into<"bool">, b: Into<"bool">): Expr<"bool">;
  or(a: Into<"bool">, b: Into<"bool">): Expr<"bool">;
  xor(a: Into<"bool">, b: Into<"bool">): Expr<"bool">;
  not(a: Into<"bool">): Expr<"bool">;
  of(a: Into<"s32">): Expr<"bool">;
  of(a: Into<"u32">): Expr<"bool">;
  of(a: Into<"s64">): Expr<"bool">;
  of(a: Into<"u64">): Expr<"bool">;
  select(a: Into<"bool">, b: Into<"bool">, c: Into<"bool">): Expr<"bool">;
}
export interface Ns_funcref extends WasmType<"funcref"> {
  null(): Expr<"funcref">;
  is_null(a: Into<"funcref">): Expr<"bool">;
  select(a: Into<"bool">, b: Into<"funcref">, c: Into<"funcref">): Expr<"funcref">;
}
export interface Ns_externref extends WasmType<"externref"> {
  null(): Expr<"externref">;
  of(x: Expr<AnyHier>): Expr<"externref">; // extern.convert_any
  is_null(a: Into<"externref">): Expr<"bool">;
  select(a: Into<"bool">, b: Into<"externref">, c: Into<"externref">): Expr<"externref">;
}
export interface Ns_exnref extends WasmType<"exnref"> {
  null(): Expr<"exnref">;
  is_null(a: Into<"exnref">): Expr<"bool">;
}
export interface Ns_anyref extends WasmType<"anyref"> {
  null(): Expr<"anyref">;
  of(x: Into<"externref">): Expr<"anyref">; // any.convert_extern
}
export interface Ns_eqref extends WasmType<"eqref"> {
  null(): Expr<"eqref">;
  eq(a: Into<"eqref">, b: Into<"eqref">): Expr<"bool">;
}
export interface Ns_i31ref extends WasmType<"i31ref"> {
  null(): Expr<"i31ref">;
  /** Boxes the LOW 31 bits. */
  of(x: I32ish): Expr<"i31ref">;
  getS(x: Into<"i31ref">): Expr<"s32">;
  getU(x: Into<"i31ref">): Expr<"u32">;
}
export interface Ns_structref extends WasmType<"structref"> {
  null(): Expr<"structref">;
}
export interface Ns_arrayref extends WasmType<"arrayref"> {
  null(): Expr<"arrayref">;
}
export interface Ns_s8x16 extends WasmType<"s8x16"> {
  const(lanes: readonly number[]): Expr<"s8x16">;
  cast(x: Expr<"u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"s8x16">;
  splat(a: Into<"s32">): Expr<"s8x16">;
  extract(v: Into<"s8x16">, lane: number): Expr<"s32">;
  replace(v: Into<"s8x16">, lane: number, value: Into<"s32">): Expr<"s8x16">;
  eq(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  ne(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  lt(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  gt(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  le(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  ge(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"m8x16">;
  add(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  sub(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  neg(a: Into<"s8x16">): Expr<"s8x16">;
  abs(a: Into<"s8x16">): Expr<"s8x16">;
  shl(a: Into<"s8x16">, b: I32ish): Expr<"s8x16">;
  shr(a: Into<"s8x16">, b: I32ish): Expr<"s8x16">;
  and(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  or(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  xor(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  andnot(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  not(a: Into<"s8x16">): Expr<"s8x16">;
  bitselect(a: Into<"s8x16">, b: Into<"s8x16">, c: Into<"m8x16">): Expr<"s8x16">;
  add_sat(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  sub_sat(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  min(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  max(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  popcnt(a: Into<"s8x16">): Expr<"s8x16">;
  swizzle(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s8x16">;
  shuffle(a: Into<"s8x16">, b: Into<"s8x16">, lanes: readonly number[]): Expr<"s8x16">;
  narrow(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s8x16">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s8x16">;
  store(mem: Memory, addr: I32ish, value: Into<"s8x16">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s8x16">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"s8x16">, lane: number, opts?: MemOpts): Expr<"s8x16">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"s8x16">, lane: number, opts?: MemOpts): void;
}
export interface Ns_u8x16 extends WasmType<"u8x16"> {
  const(lanes: readonly number[]): Expr<"u8x16">;
  cast(x: Expr<"s8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"u8x16">;
  splat(a: Into<"u32">): Expr<"u8x16">;
  extract(v: Into<"u8x16">, lane: number): Expr<"u32">;
  replace(v: Into<"u8x16">, lane: number, value: Into<"u32">): Expr<"u8x16">;
  eq(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  ne(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  lt(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  gt(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  le(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  ge(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"m8x16">;
  add(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  sub(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  neg(a: Into<"u8x16">): Expr<"u8x16">;
  shl(a: Into<"u8x16">, b: I32ish): Expr<"u8x16">;
  shr(a: Into<"u8x16">, b: I32ish): Expr<"u8x16">;
  and(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  or(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  xor(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  andnot(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  not(a: Into<"u8x16">): Expr<"u8x16">;
  bitselect(a: Into<"u8x16">, b: Into<"u8x16">, c: Into<"m8x16">): Expr<"u8x16">;
  add_sat(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  sub_sat(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  min(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  max(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  avgr(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  popcnt(a: Into<"u8x16">): Expr<"u8x16">;
  swizzle(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u8x16">;
  shuffle(a: Into<"u8x16">, b: Into<"u8x16">, lanes: readonly number[]): Expr<"u8x16">;
  narrow(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"u8x16">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u8x16">;
  store(mem: Memory, addr: I32ish, value: Into<"u8x16">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u8x16">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"u8x16">, lane: number, opts?: MemOpts): Expr<"u8x16">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"u8x16">, lane: number, opts?: MemOpts): void;
}
export interface Ns_s16x8 extends WasmType<"s16x8"> {
  const(lanes: readonly number[]): Expr<"s16x8">;
  cast(x: Expr<"s8x16" | "u8x16" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"s16x8">;
  splat(a: Into<"s32">): Expr<"s16x8">;
  extract(v: Into<"s16x8">, lane: number): Expr<"s32">;
  replace(v: Into<"s16x8">, lane: number, value: Into<"s32">): Expr<"s16x8">;
  eq(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  ne(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  lt(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  gt(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  le(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  ge(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"m16x8">;
  add(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  sub(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  neg(a: Into<"s16x8">): Expr<"s16x8">;
  mul(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  abs(a: Into<"s16x8">): Expr<"s16x8">;
  shl(a: Into<"s16x8">, b: I32ish): Expr<"s16x8">;
  shr(a: Into<"s16x8">, b: I32ish): Expr<"s16x8">;
  and(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  or(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  xor(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  andnot(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  not(a: Into<"s16x8">): Expr<"s16x8">;
  bitselect(a: Into<"s16x8">, b: Into<"s16x8">, c: Into<"m16x8">): Expr<"s16x8">;
  add_sat(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  sub_sat(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  min(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  max(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  q15mulr_sat(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s16x8">;
  extend_low(a: Into<"s8x16">): Expr<"s16x8">;
  extend_high(a: Into<"s8x16">): Expr<"s16x8">;
  extmul_low(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s16x8">;
  extmul_high(a: Into<"s8x16">, b: Into<"s8x16">): Expr<"s16x8">;
  extadd_pairwise(a: Into<"s8x16">): Expr<"s16x8">;
  load8x8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s16x8">;
  narrow(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s16x8">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s16x8">;
  store(mem: Memory, addr: I32ish, value: Into<"s16x8">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s16x8">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"s16x8">, lane: number, opts?: MemOpts): Expr<"s16x8">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"s16x8">, lane: number, opts?: MemOpts): void;
}
export interface Ns_u16x8 extends WasmType<"u16x8"> {
  const(lanes: readonly number[]): Expr<"u16x8">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"u16x8">;
  splat(a: Into<"u32">): Expr<"u16x8">;
  extract(v: Into<"u16x8">, lane: number): Expr<"u32">;
  replace(v: Into<"u16x8">, lane: number, value: Into<"u32">): Expr<"u16x8">;
  eq(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  ne(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  lt(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  gt(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  le(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  ge(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"m16x8">;
  add(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  sub(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  neg(a: Into<"u16x8">): Expr<"u16x8">;
  mul(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  shl(a: Into<"u16x8">, b: I32ish): Expr<"u16x8">;
  shr(a: Into<"u16x8">, b: I32ish): Expr<"u16x8">;
  and(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  or(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  xor(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  andnot(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  not(a: Into<"u16x8">): Expr<"u16x8">;
  bitselect(a: Into<"u16x8">, b: Into<"u16x8">, c: Into<"m16x8">): Expr<"u16x8">;
  add_sat(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  sub_sat(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  min(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  max(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  avgr(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u16x8">;
  extend_low(a: Into<"u8x16">): Expr<"u16x8">;
  extend_high(a: Into<"u8x16">): Expr<"u16x8">;
  extmul_low(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u16x8">;
  extmul_high(a: Into<"u8x16">, b: Into<"u8x16">): Expr<"u16x8">;
  extadd_pairwise(a: Into<"u8x16">): Expr<"u16x8">;
  load8x8(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u16x8">;
  narrow(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"u16x8">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u16x8">;
  store(mem: Memory, addr: I32ish, value: Into<"u16x8">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u16x8">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"u16x8">, lane: number, opts?: MemOpts): Expr<"u16x8">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"u16x8">, lane: number, opts?: MemOpts): void;
}
export interface Ns_s32x4 extends WasmType<"s32x4"> {
  const(lanes: readonly number[]): Expr<"s32x4">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"s32x4">;
  splat(a: Into<"s32">): Expr<"s32x4">;
  extract(v: Into<"s32x4">, lane: number): Expr<"s32">;
  replace(v: Into<"s32x4">, lane: number, value: Into<"s32">): Expr<"s32x4">;
  eq(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  ne(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  lt(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  gt(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  le(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  ge(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"m32x4">;
  add(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  sub(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  neg(a: Into<"s32x4">): Expr<"s32x4">;
  mul(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  abs(a: Into<"s32x4">): Expr<"s32x4">;
  shl(a: Into<"s32x4">, b: I32ish): Expr<"s32x4">;
  shr(a: Into<"s32x4">, b: I32ish): Expr<"s32x4">;
  and(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  or(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  xor(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  andnot(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  not(a: Into<"s32x4">): Expr<"s32x4">;
  bitselect(a: Into<"s32x4">, b: Into<"s32x4">, c: Into<"m32x4">): Expr<"s32x4">;
  min(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  max(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s32x4">;
  dot(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s32x4">;
  extend_low(a: Into<"s16x8">): Expr<"s32x4">;
  extend_high(a: Into<"s16x8">): Expr<"s32x4">;
  extmul_low(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s32x4">;
  extmul_high(a: Into<"s16x8">, b: Into<"s16x8">): Expr<"s32x4">;
  extadd_pairwise(a: Into<"s16x8">): Expr<"s32x4">;
  load16x4(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32x4">;
  trunc_sat(a: Into<"f32x4">): Expr<"s32x4">;
  trunc_sat_zero(a: Into<"f64x2">): Expr<"s32x4">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32x4">;
  store(mem: Memory, addr: I32ish, value: Into<"s32x4">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32x4">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s32x4">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"s32x4">, lane: number, opts?: MemOpts): Expr<"s32x4">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"s32x4">, lane: number, opts?: MemOpts): void;
}
export interface Ns_u32x4 extends WasmType<"u32x4"> {
  const(lanes: readonly number[]): Expr<"u32x4">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"u32x4">;
  splat(a: Into<"u32">): Expr<"u32x4">;
  extract(v: Into<"u32x4">, lane: number): Expr<"u32">;
  replace(v: Into<"u32x4">, lane: number, value: Into<"u32">): Expr<"u32x4">;
  eq(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  ne(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  lt(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  gt(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  le(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  ge(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"m32x4">;
  add(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  sub(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  neg(a: Into<"u32x4">): Expr<"u32x4">;
  mul(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  shl(a: Into<"u32x4">, b: I32ish): Expr<"u32x4">;
  shr(a: Into<"u32x4">, b: I32ish): Expr<"u32x4">;
  and(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  or(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  xor(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  andnot(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  not(a: Into<"u32x4">): Expr<"u32x4">;
  bitselect(a: Into<"u32x4">, b: Into<"u32x4">, c: Into<"m32x4">): Expr<"u32x4">;
  min(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  max(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u32x4">;
  extend_low(a: Into<"u16x8">): Expr<"u32x4">;
  extend_high(a: Into<"u16x8">): Expr<"u32x4">;
  extmul_low(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u32x4">;
  extmul_high(a: Into<"u16x8">, b: Into<"u16x8">): Expr<"u32x4">;
  extadd_pairwise(a: Into<"u16x8">): Expr<"u32x4">;
  load16x4(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32x4">;
  trunc_sat(a: Into<"f32x4">): Expr<"u32x4">;
  trunc_sat_zero(a: Into<"f64x2">): Expr<"u32x4">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32x4">;
  store(mem: Memory, addr: I32ish, value: Into<"u32x4">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32x4">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u32x4">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"u32x4">, lane: number, opts?: MemOpts): Expr<"u32x4">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"u32x4">, lane: number, opts?: MemOpts): void;
}
export interface Ns_s64x2 extends WasmType<"s64x2"> {
  const(lanes: readonly (number | bigint)[]): Expr<"s64x2">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"s64x2">;
  splat(a: Into<"s64">): Expr<"s64x2">;
  extract(v: Into<"s64x2">, lane: number): Expr<"s64">;
  replace(v: Into<"s64x2">, lane: number, value: Into<"s64">): Expr<"s64x2">;
  eq(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  ne(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  lt(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  gt(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  le(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  ge(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"m64x2">;
  add(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  sub(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  neg(a: Into<"s64x2">): Expr<"s64x2">;
  mul(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  abs(a: Into<"s64x2">): Expr<"s64x2">;
  shl(a: Into<"s64x2">, b: I32ish): Expr<"s64x2">;
  shr(a: Into<"s64x2">, b: I32ish): Expr<"s64x2">;
  and(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  or(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  xor(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  andnot(a: Into<"s64x2">, b: Into<"s64x2">): Expr<"s64x2">;
  not(a: Into<"s64x2">): Expr<"s64x2">;
  bitselect(a: Into<"s64x2">, b: Into<"s64x2">, c: Into<"m64x2">): Expr<"s64x2">;
  extend_low(a: Into<"s32x4">): Expr<"s64x2">;
  extend_high(a: Into<"s32x4">): Expr<"s64x2">;
  extmul_low(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s64x2">;
  extmul_high(a: Into<"s32x4">, b: Into<"s32x4">): Expr<"s64x2">;
  load32x2(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64x2">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64x2">;
  store(mem: Memory, addr: I32ish, value: Into<"s64x2">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64x2">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"s64x2">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"s64x2">, lane: number, opts?: MemOpts): Expr<"s64x2">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"s64x2">, lane: number, opts?: MemOpts): void;
}
export interface Ns_u64x2 extends WasmType<"u64x2"> {
  const(lanes: readonly (number | bigint)[]): Expr<"u64x2">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"u64x2">;
  splat(a: Into<"u64">): Expr<"u64x2">;
  extract(v: Into<"u64x2">, lane: number): Expr<"u64">;
  replace(v: Into<"u64x2">, lane: number, value: Into<"u64">): Expr<"u64x2">;
  eq(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"m64x2">;
  ne(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"m64x2">;
  add(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  sub(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  neg(a: Into<"u64x2">): Expr<"u64x2">;
  mul(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  shl(a: Into<"u64x2">, b: I32ish): Expr<"u64x2">;
  shr(a: Into<"u64x2">, b: I32ish): Expr<"u64x2">;
  and(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  or(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  xor(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  andnot(a: Into<"u64x2">, b: Into<"u64x2">): Expr<"u64x2">;
  not(a: Into<"u64x2">): Expr<"u64x2">;
  bitselect(a: Into<"u64x2">, b: Into<"u64x2">, c: Into<"m64x2">): Expr<"u64x2">;
  extend_low(a: Into<"u32x4">): Expr<"u64x2">;
  extend_high(a: Into<"u32x4">): Expr<"u64x2">;
  extmul_low(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u64x2">;
  extmul_high(a: Into<"u32x4">, b: Into<"u32x4">): Expr<"u64x2">;
  load32x2(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64x2">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64x2">;
  store(mem: Memory, addr: I32ish, value: Into<"u64x2">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64x2">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"u64x2">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"u64x2">, lane: number, opts?: MemOpts): Expr<"u64x2">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"u64x2">, lane: number, opts?: MemOpts): void;
}
export interface Ns_f32x4 extends WasmType<"f32x4"> {
  const(lanes: readonly number[]): Expr<"f32x4">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f64x2" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"f32x4">;
  splat(a: Into<"f32">): Expr<"f32x4">;
  extract(v: Into<"f32x4">, lane: number): Expr<"f32">;
  replace(v: Into<"f32x4">, lane: number, value: Into<"f32">): Expr<"f32x4">;
  eq(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  ne(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  lt(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  gt(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  le(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  ge(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"m32x4">;
  abs(a: Into<"f32x4">): Expr<"f32x4">;
  neg(a: Into<"f32x4">): Expr<"f32x4">;
  sqrt(a: Into<"f32x4">): Expr<"f32x4">;
  ceil(a: Into<"f32x4">): Expr<"f32x4">;
  floor(a: Into<"f32x4">): Expr<"f32x4">;
  trunc(a: Into<"f32x4">): Expr<"f32x4">;
  nearest(a: Into<"f32x4">): Expr<"f32x4">;
  add(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  sub(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  mul(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  div(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  min(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  max(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  pmin(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  pmax(a: Into<"f32x4">, b: Into<"f32x4">): Expr<"f32x4">;
  bitselect(a: Into<"f32x4">, b: Into<"f32x4">, c: Into<"m32x4">): Expr<"f32x4">;
  convert(a: Into<"s32x4">): Expr<"f32x4">;
  convert(a: Into<"u32x4">): Expr<"f32x4">;
  demote_zero(a: Into<"f64x2">): Expr<"f32x4">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f32x4">;
  store(mem: Memory, addr: I32ish, value: Into<"f32x4">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f32x4">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f32x4">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"f32x4">, lane: number, opts?: MemOpts): Expr<"f32x4">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"f32x4">, lane: number, opts?: MemOpts): void;
}
export interface Ns_f64x2 extends WasmType<"f64x2"> {
  const(lanes: readonly number[]): Expr<"f64x2">;
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "m8x16" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "m8x16" | "m16x8" | "m32x4" | "m64x2">): Expr<"f64x2">;
  splat(a: Into<"f64">): Expr<"f64x2">;
  extract(v: Into<"f64x2">, lane: number): Expr<"f64">;
  replace(v: Into<"f64x2">, lane: number, value: Into<"f64">): Expr<"f64x2">;
  eq(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  ne(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  lt(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  gt(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  le(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  ge(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"m64x2">;
  abs(a: Into<"f64x2">): Expr<"f64x2">;
  neg(a: Into<"f64x2">): Expr<"f64x2">;
  sqrt(a: Into<"f64x2">): Expr<"f64x2">;
  ceil(a: Into<"f64x2">): Expr<"f64x2">;
  floor(a: Into<"f64x2">): Expr<"f64x2">;
  trunc(a: Into<"f64x2">): Expr<"f64x2">;
  nearest(a: Into<"f64x2">): Expr<"f64x2">;
  add(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  sub(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  mul(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  div(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  min(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  max(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  pmin(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  pmax(a: Into<"f64x2">, b: Into<"f64x2">): Expr<"f64x2">;
  bitselect(a: Into<"f64x2">, b: Into<"f64x2">, c: Into<"m64x2">): Expr<"f64x2">;
  convert_low(a: Into<"s32x4">): Expr<"f64x2">;
  convert_low(a: Into<"u32x4">): Expr<"f64x2">;
  promote_low(a: Into<"f32x4">): Expr<"f64x2">;
  load(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f64x2">;
  store(mem: Memory, addr: I32ish, value: Into<"f64x2">, opts?: MemOpts): void;
  load_splat(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f64x2">;
  load_zero(mem: Memory, addr: I32ish, opts?: MemOpts): Expr<"f64x2">;
  load_lane(mem: Memory, addr: I32ish, v: Into<"f64x2">, lane: number, opts?: MemOpts): Expr<"f64x2">;
  store_lane(mem: Memory, addr: I32ish, v: Into<"f64x2">, lane: number, opts?: MemOpts): void;
}
export interface Ns_m8x16 extends WasmType<"m8x16"> {
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m16x8" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m16x8" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m16x8" | "m32x4" | "m64x2">): Expr<"m8x16">;
  and(a: Into<"m8x16">, b: Into<"m8x16">): Expr<"m8x16">;
  or(a: Into<"m8x16">, b: Into<"m8x16">): Expr<"m8x16">;
  xor(a: Into<"m8x16">, b: Into<"m8x16">): Expr<"m8x16">;
  andnot(a: Into<"m8x16">, b: Into<"m8x16">): Expr<"m8x16">;
  not(a: Into<"m8x16">): Expr<"m8x16">;
  any_true(a: Into<"m8x16">): Expr<"bool">;
  all_true(a: Into<"m8x16">): Expr<"bool">;
  bitmask(a: Into<"m8x16">): Expr<"u32">;
}
export interface Ns_m16x8 extends WasmType<"m16x8"> {
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m32x4" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m32x4" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m32x4" | "m64x2">): Expr<"m16x8">;
  and(a: Into<"m16x8">, b: Into<"m16x8">): Expr<"m16x8">;
  or(a: Into<"m16x8">, b: Into<"m16x8">): Expr<"m16x8">;
  xor(a: Into<"m16x8">, b: Into<"m16x8">): Expr<"m16x8">;
  andnot(a: Into<"m16x8">, b: Into<"m16x8">): Expr<"m16x8">;
  not(a: Into<"m16x8">): Expr<"m16x8">;
  any_true(a: Into<"m16x8">): Expr<"bool">;
  all_true(a: Into<"m16x8">): Expr<"bool">;
  bitmask(a: Into<"m16x8">): Expr<"u32">;
}
export interface Ns_m32x4 extends WasmType<"m32x4"> {
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m64x2"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m64x2"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m64x2">): Expr<"m32x4">;
  and(a: Into<"m32x4">, b: Into<"m32x4">): Expr<"m32x4">;
  or(a: Into<"m32x4">, b: Into<"m32x4">): Expr<"m32x4">;
  xor(a: Into<"m32x4">, b: Into<"m32x4">): Expr<"m32x4">;
  andnot(a: Into<"m32x4">, b: Into<"m32x4">): Expr<"m32x4">;
  not(a: Into<"m32x4">): Expr<"m32x4">;
  any_true(a: Into<"m32x4">): Expr<"bool">;
  all_true(a: Into<"m32x4">): Expr<"bool">;
  bitmask(a: Into<"m32x4">): Expr<"u32">;
}
export interface Ns_m64x2 extends WasmType<"m64x2"> {
  cast(x: Expr<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4"> | Var<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4"> | Global<"s8x16" | "u8x16" | "s16x8" | "u16x8" | "s32x4" | "u32x4" | "s64x2" | "u64x2" | "f32x4" | "f64x2" | "m8x16" | "m16x8" | "m32x4">): Expr<"m64x2">;
  and(a: Into<"m64x2">, b: Into<"m64x2">): Expr<"m64x2">;
  or(a: Into<"m64x2">, b: Into<"m64x2">): Expr<"m64x2">;
  xor(a: Into<"m64x2">, b: Into<"m64x2">): Expr<"m64x2">;
  andnot(a: Into<"m64x2">, b: Into<"m64x2">): Expr<"m64x2">;
  not(a: Into<"m64x2">): Expr<"m64x2">;
  any_true(a: Into<"m64x2">): Expr<"bool">;
  all_true(a: Into<"m64x2">): Expr<"bool">;
  bitmask(a: Into<"m64x2">): Expr<"u32">;
}

export const s32: Ns_s32;
export const u32: Ns_u32;
export const s64: Ns_s64;
export const u64: Ns_u64;
export const f32: Ns_f32;
export const f64: Ns_f64;
export const bool: Ns_bool;
export const funcref: Ns_funcref;
export const externref: Ns_externref;
export const exnref: Ns_exnref;
export const anyref: Ns_anyref;
export const eqref: Ns_eqref;
export const i31ref: Ns_i31ref;
export const structref: Ns_structref;
export const arrayref: Ns_arrayref;
export const s8x16: Ns_s8x16;
export const u8x16: Ns_u8x16;
export const s16x8: Ns_s16x8;
export const u16x8: Ns_u16x8;
export const s32x4: Ns_s32x4;
export const u32x4: Ns_u32x4;
export const s64x2: Ns_s64x2;
export const u64x2: Ns_u64x2;
export const f32x4: Ns_f32x4;
export const f64x2: Ns_f64x2;
export const m8x16: Ns_m8x16;
export const m16x8: Ns_m16x8;
export const m32x4: Ns_m32x4;
export const m64x2: Ns_m64x2;
