import { VENEER_OPS } from "../src/expr.js";

/**
 * Generate index.d.ts from the veneer registry. The instruction constructors
 * are attached to the type namespaces dynamically, so tsc-from-JSDoc cannot
 * see them — VENEER_OPS is the single machine-readable source of truth for
 * every overload (the same registry the sweep tests execute), and a
 * hand-maintained skeleton covers Module, handles, and the `$` context.
 *
 * Run via `npm run types`; test/dts.test.js fails if the committed file is
 * stale.
 */

const SCALARS = ["s32", "u32", "s64", "u64", "f32", "f64", "bool", "funcref", "externref", "exnref"];
const VECS = ["s8x16", "u8x16", "s16x8", "u16x8", "s32x4", "u32x4", "s64x2", "u64x2", "f32x4", "f64x2"];
const MASKS = ["m8x16", "m16x8", "m32x4", "m64x2"];
const ALL = [...SCALARS, ...VECS, ...MASKS];

// Safe value-exact promotion (DESIGN.md): what an operand slot of type T accepts.
const ACCEPTS = {
  s32: ["s32", "bool"],
  u32: ["u32", "bool"],
  s64: ["s64", "s32", "u32", "bool"],
  u64: ["u64", "u32", "bool"],
  f32: ["f32", "bool"],
  f64: ["f64", "f32", "s32", "u32", "bool"],
};

// Zero-cost casts: scalars within a storage width, v128 views into each other.
const CASTS = {
  s32: ["u32", "bool"],
  u32: ["s32", "bool"],
  s64: ["u64"],
  u64: ["s64"],
};
for (const v of [...VECS, ...MASKS]) CASTS[v] = [...VECS, ...MASKS].filter((x) => x !== v);

const CONSTS = {
  s32: "value: number", u32: "value: number",
  s64: "value: number | bigint", u64: "value: number | bigint",
  f32: "value: number", f64: "value: number",
  bool: "value: boolean",
  s8x16: "lanes: readonly number[]", u8x16: "lanes: readonly number[]",
  s16x8: "lanes: readonly number[]", u16x8: "lanes: readonly number[]",
  s32x4: "lanes: readonly number[]", u32x4: "lanes: readonly number[]",
  s64x2: "lanes: readonly (number | bigint)[]", u64x2: "lanes: readonly (number | bigint)[]",
  f32x4: "lanes: readonly number[]", f64x2: "lanes: readonly number[]",
};

const ARG = ["a", "b", "c"];
const into = (t) => `Into<"${t.name}">`;
const expr = (t) => `Expr<"${t.name}">`;
const ret = (results) => (results.length ? expr(results[0]) : "void");

function memberFor(v) {
  const params = v.params;
  const argOf = (p, i) => `${ARG[i]}: ${v.any32?.[i] ? "I32ish" : into(p)}`;
  if (v.mem === "load" || v.mem === "store") {
    if (v.laneCount) {
      const r = v.mem === "load" ? ret(v.results) : "void";
      return `${v.name}(mem: Memory, addr: I32ish, v: ${into(params[0])}, lane: number, opts?: MemOpts): ${r};`;
    }
    if (v.mem === "load") return `${v.name}(mem: Memory, addr: I32ish, opts?: MemOpts): ${ret(v.results)};`;
    return `${v.name}(mem: Memory, addr: I32ish, value: ${into(params[1])}, opts?: MemOpts): void;`;
  }
  if (v.shuffle) {
    return `shuffle(a: ${into(params[0])}, b: ${into(params[1])}, lanes: readonly number[]): ${ret(v.results)};`;
  }
  if (v.laneCount) {
    if (v.name === "extract") return `extract(v: ${into(params[0])}, lane: number): ${ret(v.results)};`;
    return `replace(v: ${into(params[0])}, lane: number, value: ${into(params[1])}): ${ret(v.results)};`;
  }
  const args = params.map(argOf).join(", ");
  return `${v.name}(${args}): ${ret(v.results)};`;
}

export function generateDts() {
  const lines = [];
  const push = (s = "") => lines.push(s);

  push("// Generated by scripts/generate-dts.js from the veneer registry — do not edit.");
  push("// Regenerate with `npm run types`; test/dts.test.js fails when this is stale.");
  push("");
  push(`export type TypeName =\n  ${ALL.map((n) => `"${n}"`).join(" | ")};`);
  push("");
  push("/** Typed function reference brand: (ref $sig) / (ref null $sig). */");
  push("export type RefBrand<");
  push("  P extends readonly WasmType[] = any, R extends readonly WasmType[] = any,");
  push("  N extends boolean = boolean> = { readonly __refParams: P; readonly __refResults: R; readonly __nullable: N };");
  push("export type TypeTag = TypeName | RefBrand;");
  push("");
  push("/** A single-value expression of builder-level type T. */");
  push("export interface Expr<T extends TypeTag = TypeTag> {");
  push("  readonly __wasmloom: T;");
  push("}");
  push("");
  push("/** Safe value-exact promotion: what an operand slot of type T accepts. */");
  push("type Accepts = {");
  for (const n of ALL) {
    push(`  ${n}: ${(ACCEPTS[n] ?? [n]).map((x) => `"${x}"`).join(" | ")};`);
  }
  push("};");
  push("// funcref slots also take any typed function reference (upcast promotion);");
  push("// nullable ref slots take the non-null form (structural: false <: boolean).");
  push("export type Into<T extends TypeTag> =");
  push("  T extends \"funcref\" ? Expr<\"funcref\"> | Expr<RefBrand>");
  push("  : T extends keyof Accepts ? Expr<Accepts[T] & TypeName>");
  push("  : T extends RefBrand<infer P, infer R, infer N>");
  push("    ? (N extends true ? Expr<RefBrand<P, R, boolean>> : Expr<RefBrand<P, R, false>>)");
  push("  : never;");
  push('type I32ish = Expr<"s32" | "u32" | "bool">; // sign-agnostic 32-bit positions');
  push("");
  push("export interface MemOpts {");
  push("  /** byte alignment hint, a power of two ≤ the access size (default: natural) */");
  push("  align?: number;");
  push("  /** constant byte offset added to the address (default: 0) */");
  push("  offset?: number;");
  push("}");
  push("");
  push("/** The value-level face of a type: a token for declarations. */");
  push("export interface WasmType<T extends TypeTag = TypeTag> {");
  push("  readonly name: string;");
  push("  readonly __type?: T;");
  push("}");
  push("");
  push("type NameOf<W> = W extends WasmType<infer T> ? T : never;");
  push("type VarsOf<P extends readonly WasmType[]> = { [K in keyof P]: Var<NameOf<P[K]>> };");
  push("type IntoArgs<P extends readonly WasmType[]> = { [K in keyof P]: Into<NameOf<P[K]>> };");
  push("type CallResult<R extends readonly WasmType[]> =");
  push("  R extends readonly [] ? void : R extends readonly [WasmType<infer T>] ? Expr<T> : VarsOf<R>;");
  push("");
  push("/** A function-scoped variable (wasm local). Reads by using it as a value. */");
  push("export interface Var<T extends TypeTag = TypeTag> extends Expr<T> {");
  push("  set(value: Into<T>): void;");
  push("}");
  push("");
  push("/** A module-scoped variable (wasm global). */");
  push("export interface Global<T extends TypeTag = TypeTag> extends Expr<T> {");
  push("  set(value: Into<T>): void;");
  push("  import(module: string, name: string): this;");
  push("  export(name: string): this;");
  push("  immutable(): this;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("export interface Label {");
  push("  /** Pin a forward-declared label at the current position. Exactly once. */");
  push("  here(): Label;");
  push("}");
  push("");
  push("export interface IfChain<R extends readonly WasmType[]> {");
  push("  elseIf(cond: Into<\"bool\">, body: (ctx: Ctx<R>) => void): IfChain<R>;");
  push("  else(body: (ctx: Ctx<R>) => void): void;");
  push("}");
  push("");
  push("/** The `$` statement context passed to body callbacks. */");
  push("export interface Ctx<R extends readonly WasmType[] = WasmType[]> {");
  push("  label: { (): Label; ahead(): Label };");
  push("  variable<W extends WasmType>(type: W, init?: Into<NameOf<W>> | number | bigint | boolean): Var<NameOf<W>>;");
  push("  goto(target: Label): void;");
  push("  gotoIf(cond: Into<\"bool\">, target: Label): void;");
  push("  switch(index: I32ish, targets: readonly Label[], defaultTarget: Label): void;");
  push("  /** Returning a call's results directly emits a tail call (return_call). */");
  push("  return(...values: IntoArgs<R>): void;");
  push("  /** Throw an exception with the tag's payload. A terminator, like return. */");
  push("  throw<CP extends readonly WasmType[]>(tag: Tag<CP>, ...args: IntoArgs<CP>): void;");
  push("  /** Rethrow a caught exception (exnref), preserving its identity. */");
  push("  throwRef(exn: Into<\"exnref\">): void;");
  push("  /** Protected region; handlers chain after. Bodies are control-flow islands. */");
  push("  try(body: (ctx: Ctx<R>) => void): TryChain<R>;");
  push("  drop(value: Expr): void;");
  push("  unreachable(): void;");
  push("  if(cond: Into<\"bool\">, body: (ctx: Ctx<R>) => void): IfChain<R>;");
  push("  while(cond: Into<\"bool\">, body: (ctx: Ctx<R>) => void): void;");
  push("}");
  push("");
  push("export interface Func<P extends readonly WasmType[] = WasmType[], R extends readonly WasmType[] = WasmType[]> {");
  push("  body(cb: (...args: [...VarsOf<P>, Ctx<R>]) => void): this;");
  push("  import(module: string, name: string): this;");
  push("  export(name: string): this;");
  push("  /** Precise non-null reference (ref $sig); upcasts are promotions. */");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("  ref(): Expr<RefBrand<P, R, false>>;");
  push("  /** This function's signature as an interned funcType handle. */");
  push("  readonly type: FuncType<P, R>;");
  push("  call(...args: IntoArgs<P>): CallResult<R>;");
  push("}");
  push("");
  push("export interface NonNullRefType<P extends readonly WasmType[], R extends readonly WasmType[]>");
  push("  extends WasmType<RefBrand<P, R, false>> {");
  push("  /** Checked nullable\u2192non-null bridge (ref.as_non_null \u2014 traps on null). */");
  push("  of(x: Expr<RefBrand<P, R, boolean>>): Expr<RefBrand<P, R, false>>;");
  push("}");
  push("export interface NullableRefType<P extends readonly WasmType[], R extends readonly WasmType[]>");
  push("  extends WasmType<RefBrand<P, R, true>> {");
  push("  null(): Expr<RefBrand<P, R, true>>;");
  push("  is_null(x: Expr<RefBrand<P, R, boolean>>): Expr<\"bool\">;");
  push("}");
  push("export interface FuncType<P extends readonly WasmType[] = WasmType[], R extends readonly WasmType[] = WasmType[]> {");
  push("  readonly params: P;");
  push("  readonly results: R;");
  push("  /** (ref $sig) \u2014 non-null typed function reference type. */");
  push("  readonly ref: NonNullRefType<P, R>;");
  push("  /** (ref null $sig). */");
  push("  readonly refNull: NullableRefType<P, R>;");
  push("  /** call_ref through a typed reference (traps on null). Tail in $.return. */");
  push("  call(ref: Expr<RefBrand<P, R, boolean>>, ...args: IntoArgs<P>): CallResult<R>;");
  push("}");
  push("");
  push("/** An exception tag: the typed signature of thrown values (wasm 3.0 EH). */");
  push("export interface Tag<P extends readonly WasmType[] = WasmType[]> {");
  push("  readonly params: P;");
  push("  import(module: string, name: string): this;");
  push("  export(name: string): this;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("export interface TryChain<R extends readonly WasmType[]> {");
  push("  /** First matching clause wins; the payload arrives as typed variables. */");
  push("  catch<CP extends readonly WasmType[]>(");
  push("    tag: Tag<CP>, cb: (...args: [...VarsOf<CP>, Ctx<R>]) => void): TryChain<R>;");
  push("  /** Like catch, plus an exnref for $.throwRef rethrows. */");
  push("  catchRef<CP extends readonly WasmType[]>(");
  push("    tag: Tag<CP>, cb: (...args: [...VarsOf<CP>, Var<\"exnref\">, Ctx<R>]) => void): TryChain<R>;");
  push("  catchAll(cb: (ctx: Ctx<R>) => void): TryChain<R>;");
  push("  catchAllRef(cb: (exn: Var<\"exnref\">, ctx: Ctx<R>) => void): TryChain<R>;");
  push("}");
  push("");
  push("export interface Limits { min: number; max?: number }");
  push("");
  push("export interface Memory {");
  push("  size(): Expr<\"u32\">;");
  push("  grow(delta: I32ish): Expr<\"u32\">;");
  push("  fill(dst: I32ish, value: I32ish, len: I32ish): void;");
  push("  copy(dst: I32ish, src: I32ish, len: I32ish, opts?: { from?: Memory }): void;");
  push("  init(seg: DataSegment, dst: I32ish, src: I32ish, len: I32ish): void;");
  push("  import(module: string, name: string): this;");
  push("  export(name: string): this;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("export interface Table<E extends TypeTag = \"funcref\"> {");
  push("  get(index: I32ish): Expr<E>;");
  push("  set(index: I32ish, value: Into<E>): void;");
  push("  size(): Expr<\"u32\">;");
  push("  grow(delta: I32ish, init?: Into<E>): Expr<\"u32\">;");
  push("  fill(start: I32ish, value: Into<E>, len: I32ish): void;");
  push("  copy(dst: I32ish, src: I32ish, len: I32ish, opts?: { from?: Table<E> }): void;");
  push("  init(seg: ElemSegment, dst: I32ish, src: I32ish, len: I32ish): void;");
  push("  call<P extends readonly WasmType[], R extends readonly WasmType[]>(");
  push("    type: FuncType<P, R>, index: I32ish, ...args: IntoArgs<P>): CallResult<R>;");
  push("  import(module: string, name: string): this;");
  push("  export(name: string): this;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("type ConstOffset = number | Expr<\"s32\" | \"u32\"> | Global<\"s32\" | \"u32\">;");
  push("");
  push("export interface DataSegment {");
  push("  at(mem: Memory, offset: ConstOffset): this;");
  push("  drop(): void;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("export interface ElemSegment {");
  push("  at(table: Table<any>, offset: ConstOffset): this;");
  push("  drop(): void;");
  push("  /** Debug name for the name section (overrides export/import-derived). */");
  push("  name(name: string): this;");
  push("}");
  push("");
  push("type GlobalInit<T extends TypeTag> =");
  push("  Into<T> | Global<T> | null | number | bigint | boolean | readonly (number | bigint)[];");
  push("");
  push("export class Module {");
  push("  constructor(opts?: { debug?: boolean; permissive?: boolean; tailCalls?: boolean; names?: boolean });");
  push("  function<const P extends readonly WasmType[], const R extends readonly WasmType[]>(params: P, results: R): Func<P, R>;");
  push("  function<P extends readonly WasmType[], R extends readonly WasmType[]>(type: FuncType<P, R>): Func<P, R>;");
  push("  funcType<const P extends readonly WasmType[], const R extends readonly WasmType[]>(params: P, results: R): FuncType<P, R>;");
  push("  variable<W extends WasmType>(type: W, init?: GlobalInit<NameOf<W>>): Global<NameOf<W>>;");
  push("  tag<const P extends readonly WasmType[]>(params: P): Tag<P>;");
  push("  memory(limits: Limits): Memory;");
  push("  table<E extends WasmType<\"funcref\"> | WasmType<\"externref\"> | NullableRefType<readonly WasmType[], readonly WasmType[]>>(");
  push("    elemType: E, limits: Limits): Table<NameOf<E>>;");
  push("  data(bytes: Uint8Array | ArrayBuffer): DataSegment;");
  push("  elem(items: readonly (Func<any, any> | null)[]): ElemSegment;");
  push("  start(fn: Func<any, any>): this;");
  push("  /** Module debug name for the name section. */");
  push("  name(name: string): this;");
  push("  emit(): Uint8Array;");
  push("}");
  push("");
  push("export class WasmLoomError extends Error {}");
  push("");

  // Namespace interfaces from the registry.
  for (const name of ALL) {
    const iface = `Ns_${name}`;
    push(`export interface ${iface} extends WasmType<"${name}"> {`);
    if (CONSTS[name]) push(`  const(${CONSTS[name]}): Expr<"${name}">;`);
    if (CASTS[name]) {
      const from = CASTS[name].map((x) => `"${x}"`).join(" | ");
      push(`  cast(x: Expr<${from}> | Var<${from}> | Global<${from}>): Expr<"${name}">;`);
    }
    if (name === "funcref" || name === "externref" || name === "exnref") push(`  null(): Expr<"${name}">;`);
    const seen = new Set();
    for (const v of VENEER_OPS) {
      if (v.ns !== name || v.mem === "bulk") continue;
      const member = memberFor(v);
      if (seen.has(member)) continue; // e.g. shared entries registered per signedness
      seen.add(member);
      push(`  ${member}`);
    }
    push("}");
  }
  push("");
  for (const name of ALL) push(`export const ${name}: Ns_${name};`);
  push("");
  return lines.join("\n");
}

// Run directly: write index.d.ts at the repo root.
if (import.meta.url === `file://${process.argv[1]}`) {
  const { writeFileSync } = await import("node:fs");
  const { fileURLToPath } = await import("node:url");
  const path = new URL("../index.d.ts", import.meta.url);
  writeFileSync(fileURLToPath(path), generateDts());
  console.log("wrote index.d.ts");
}
